--SQlite
SELECT l.ID as ID, l.START_DATE as START_DATE, l.END_DATE as END_DATE, l.TOTAL as TOTAL, ct.NAME as CUSTOMER_NAME, c.NAME as CAR_NAME, e.NAME as EMPLOYEE_NAME
FROM LOCATIONS l
JOIN CUSTOMERS ct ON l.CUSTOMER_ID = ct.ID
JOIN CARS c ON l.CAR_ID = c.ID
JOIN EMPLOYEES e ON l.EMPLOYEE_ID = e.ID;

SELECT COUNT(*) as LOCATIONS_COUNT
FROM LOCATIONS;

SELECT l.ID as ID, l.START_DATE as START_DATE, l.END_DATE as END_DATE, l.TOTAL as TOTAL, ct.NAME as CUSTOMER_NAME, c.NAME as CAR_NAME, e.NAME as EMPLOYEE_NAME
FROM LOCATIONS l
JOIN CUSTOMERS ct ON l.CUSTOMER_ID = ct.ID
JOIN CARS c ON l.CAR_ID = c.ID
JOIN EMPLOYEES e ON l.EMPLOYEE_ID = e.ID
ORDER BY l.TOTAL DESC
LIMIT 1;

SELECT l.ID as ID, l.START_DATE as START_DATE, l.END_DATE as END_DATE, l.TOTAL as TOTAL, ct.NAME as CUSTOMER_NAME, c.NAME as CAR_NAME, e.NAME as EMPLOYEE_NAME
FROM LOCATIONS l
JOIN CUSTOMERS ct ON l.CUSTOMER_ID = ct.ID
JOIN CARS c ON l.CAR_ID = c.ID
JOIN EMPLOYEES e ON l.EMPLOYEE_ID = e.ID
WHERE l.START_DATE BETWEEN '2022-05-22' AND '2022-12-25';
