--SQlite
SELECT NAME, LASTNAME, EMAIL FROM CUSTOMERS WHERE STATE = 'SP';

SELECT * FROM CARS WHERE STATUS = 'Liberado';

SELECT * FROM CARS WHERE YEAR = 2016;

SELECT e.NAME AS Employee_Name, e.PHONE AS Employee_Phone, e.CONTRACT_DATE AS Contract_Date, p.DESCRIPTION AS Position
FROM EMPLOYEES e
JOIN POSITIONS p ON e.POSITION_ID = p.ID;

SELECT e.NAME AS Employee_name, COUNT(l.ID) AS Total_Locations
FROM EMPLOYEES e
JOIN LOCATIONS l ON e.ID = l.EMPLOYEE_ID
GROUP BY e.NAME
HAVING COUNT(l.ID) >= 2;

SELECT c.NAME AS Customer_Name, COUNT(l.ID) AS Total_Locations
FROM CUSTOMERS c
JOIN LOCATIONS l ON c.ID = l.CUSTOMER_ID
GROUP BY c.NAME
HAVING COUNT(l.ID) >= 2;
