-- SQLite
INSERT INTO CAR_MODELS (MODEL_NAME) VALUES ('Conversível');
INSERT INTO CAR_MODELS (MODEL_NAME) VALUES ('Sedã');
INSERT INTO CAR_MODELS (MODEL_NAME) VALUES ('Hatch');
INSERT INTO CAR_MODELS (MODEL_NAME) VALUES ('Coupé');
INSERT INTO CAR_MODELS (MODEL_NAME) VALUES ('Perua');
INSERT INTO CAR_MODELS (MODEL_NAME) VALUES ('SUV');
INSERT INTO CAR_MODELS (MODEL_NAME) VALUES ('Picape');
INSERT INTO CAR_MODELS (MODEL_NAME) VALUES ('Minivan');
INSERT INTO CAR_MODELS (MODEL_NAME) VALUES ('Utilitário');
INSERT INTO CAR_MODELS (MODEL_NAME) VALUES ('Buggy');
