-- SQLite
INSERT INTO CAR_BRANDS (BRAND_NAME) VALUES ('Chevrolet');
INSERT INTO CAR_BRANDS (BRAND_NAME) VALUES ('Toyota');
INSERT INTO CAR_BRANDS (BRAND_NAME) VALUES ('Hyundai');
INSERT INTO CAR_BRANDS (BRAND_NAME) VALUES ('Volkswagen');
INSERT INTO CAR_BRANDS (BRAND_NAME) VALUES ('Jeep');
INSERT INTO CAR_BRANDS (BRAND_NAME) VALUES ('Renault');
INSERT INTO CAR_BRANDS (BRAND_NAME) VALUES ('Honda');
INSERT INTO CAR_BRANDS (BRAND_NAME) VALUES ('Fiat');
