--SQlite
UPDATE CUSTOMERS SET EMAIL = 'carolina@campuscode.com.br' WHERE ID = 9;
UPDATE CUSTOMERS SET BIRTH_DATE = '1986-06-19' WHERE ID = 4;
UPDATE CARS SET YEAR = 2019 WHERE ID = 4;
DELETE FROM CARS WHERE ID = 2;

ALTER TABLE CUSTOMERS RENAME COLUMN PHONE TO PHONE_NUMBER;
